#version: '2'

#services:
  ghost:
    image: ghost
    container_name: ghost
    ports:
      - "2368:2368"
    volumes:
      - ./ghost/config.js:/var/lib/ghost/config.js
      - ./ghost/theme/:/var/lib/ghost/theme/
      - ./ghost/data/:/var/lib/ghost/data/
    environment:
      - NODE_ENV=production
      - GHOST_BASE_URL=http://example.com/  # Change this to your URL
  nginx:
    image: nginx 
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/keys/:/etc/nginx/keys/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - ghost 
